feat: add neonbee-kickstart-guide
neonbee-project/neonbee-examples pull request #1
Opened 2022-12-21 15:18 UTC by pk-work

2023-01-02 08:54 UTC, s4heid requested changes
cool code examples! just some minor things I noticed.

2023-01-02 08:54 UTC, s4heid commented on neonbee-kickstart-guide/README.md
> +                createDummyDataVerticle(QUALIFIED_NAME).withStaticResponse(new JsonArray().add(BEEHIVE_1));
nit; no static import to make it more explicit which verticle's qualified name you are using

2023-01-02 08:54 UTC, s4heid commented on neonbee-kickstart-guide/README.md
> +
maybe add some explanation of the example model, e.g.:

```suggestion
A CDS model is a way of organizing and defining the data and relationships within a service. It specifies the entities, their fields, and any relationships between them. In this case, the model consists of the `BeehiveService` and the `Beehives` entity, and defines the structure and content of the data stored in the service. The Beehives entity has a key field called "id", which is an integer, and four other fields: "queen", "drones", "worker", and "population". These fields represent different aspects of a beehive, such as the type of bees present or the size of the hive's population.
```

2023-01-02 08:54 UTC, s4heid commented on neonbee-kickstart-guide/README.md
> +2. ... define the OData model of your data in CDS.
```suggestion
2. ... define the OData model of your data in [Common Data Service (CDS)](https://cap.cloud.sap/docs/cds/).
```

2023-01-02 08:54 UTC, s4heid commented on neonbee-kickstart-guide/README.md
> +The purpose of *EntityVerticles* is to process structured data. Now that you have defied a data structure in the CDS file,
typo
```suggestion
The purpose of *EntityVerticles* is to process structured data. Now that you have defined a data structure in the CDS file,
```

2023-01-02 08:54 UTC, s4heid commented on neonbee-kickstart-guide/gradle/checkstyle/test.xml
> +        <!-- JavaDoc Checks See http://checkstyle.org/config_javadoc.html -->
i guess you can delete this?

2023-01-02 08:54 UTC, s4heid commented on neonbee-kickstart-guide/gradlew
> +# Copyright © 2015-2021 the original authors.
update license year?
```suggestion
# Copyright © 2015-2023 the original authors.
```

2023-01-03 08:50 UTC, pk-work commented on neonbee-kickstart-guide/gradle/checkstyle/test.xml
> +        <!-- JavaDoc Checks See http://checkstyle.org/config_javadoc.html -->
Yes, but it was added by the plugin.

2023-01-03 08:51 UTC, pk-work commented on neonbee-kickstart-guide/gradlew
> +# Copyright © 2015-2021 the original authors.
This file was generated by gradle, so I will not touch it.

2023-01-03 09:12 UTC, merged